version: 0.2
phases:
 pre_build:
  commands:
    - echo "In pre build phase"
 build:
  commands:
    - echo "In build phase"
    - mvn clean compile war:war 
 post_build:
  commands:
   - echo "deployment completed successfully.."
   - mv target/aws-code-build-demo-0.0.1-SNAPSHOT.war aws-code-build-demo-0.0.1-SNAPSHOT.war
artifacts:
 files:
  - aws-code-build-demo-0.0.1-SNAPSHOT.war
  - .ebextensions/**/*
discard-paths: yes