version: 0.2
phases:
 pre_build:
  commands:
    - echo "In pre build phase"
 build:
  commands:
    - echo "In build phase"
    - mvn clean compile war:war 
 post_build:
  commands:
   - echo "deployment completed successfully"
artifacts:
 files:
  - target/**/*